server:
  port: 9090
  servlet:
    context-path: /issac
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    # 注册数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true
    username: root
    password: rootroot
  # 连接单机Redis
  redis:
    host: localhost
    port: 6379
    # 连接redis 集群
#    sentinel:
#      master: mymaster
#      nodes: sentinel1:26379,sentinel2:26379,sentinel3:26379
  # 指定缓存类型
  cache:
    type: redis
    # 设置缓存名称
    cache-names: realTimeCache

mybatis:
  # 注册映射文件
  mapper-locations: classpath:com/issac/spring/boot/mybatis/dao/EmployeeDao.xml
  # 注册实体类别名
  type-aliases-package: com.issac.spring.boot.mybatis.po

# 日志文件配置
logging:
  level:
    root: warn
    com.issac.spring.boot.mybatis.dao: debug
  pattern:
    console: xxx:%level %msg%n










